### PR TITLE
JRE is now v15

### PR DESCRIPTION
**Pull request by Bretterteig**
yed is now on JRE15

### CODE REVIEW

**Comment by 48kRAM** [comment]
They've also changed their product URL slightly:

http://www.yworks.com/products/ -> https://www.yworks.com/resources/

**Comment by 48kRAM** [comment]
Is this actually working today? (I don't have a Mac handy to test right now.) It looks like their "CurrentVersion" file is out of date and I'm hoping they haven't abandoned it.

**Comment by Bretterteig** [comment]
Thanks for the info. I just checked the URL and only the one for the actual download changed. While browsing the website I haven't noticed it.

I would assume that they will abandon the version file. I just downloaded the the yED site via curl and found that URLTextSearcher could be used for future releases.

**Comment by 48kRAM** [comment]
Are you going to submit a new PR for that then? (Thank you, if so)

**Comment by Bretterteig** [comment]
I will do that :)

**Pull request closed without merging**
